name: Lint and Format

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint-and-format:
    name: Run Linters and Formatters
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4
        
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"
        
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install ".[dev]"
        
        - name: Run ruff linter
          run: |
            ruff check src/radius_clustering tests --fix
        
        - name: Run black formatter
          run: |
            black src/radius_clustering tests --check

